const router = require('express').Router();

const majke =
    [
      {
        jmbg: 6633137800084,
        ime: "Darron",
        djevojackoPrezime: "Medhurst",
        prezime: "Auer",
        datumRodjenja: "1952-04-01T23:33:42.808Z",
        mjestoRodjenja: "New Mandy",
        opstinaRordjenja: "New Mandy",
        drzava: "BIH",
        postanskiBroj: "44651",
        adresa: "55680 Holden Wall Apt. 742",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Internal Group Orchestrator"
      },
      {
        jmbg: 1756669695080,
        ime: "Ressie",
        djevojackoPrezime: "Spinka",
        prezime: "Padberg",
        datumRodjenja: "1980-07-09T15:07:00.851Z",
        mjestoRodjenja: "South Morganhaven",
        opstinaRordjenja: "South Morganhaven",
        drzava: "BIH",
        postanskiBroj: "25174-8403",
        adresa: "7061 Samanta Rue Suite 863",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Legacy Functionality Analyst"
      },
      {
        jmbg: 9694189415859,
        ime: "Valerie",
        djevojackoPrezime: "Greenholt",
        prezime: "Nienow",
        datumRodjenja: "1961-11-23T15:58:00.731Z",
        mjestoRodjenja: "Port Harmon",
        opstinaRordjenja: "Port Harmon",
        drzava: "BIH",
        postanskiBroj: "22206",
        adresa: "84442 Rosenbaum Square Suite 828",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Direct Identity Manager"
      },
      {
        jmbg: 6258986419988,
        ime: "Annetta",
        djevojackoPrezime: "Batz",
        prezime: "Okuneva",
        datumRodjenja: "1955-06-22T01:13:17.090Z",
        mjestoRodjenja: "Bridgetchester",
        opstinaRordjenja: "Bridgetchester",
        drzava: "BIH",
        postanskiBroj: "02485-8495",
        adresa: "50742 Christina Court Apt. 800",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Global Interactions Consultant"
      },
      {
        jmbg: 1437442927145,
        ime: "Alessandro",
        djevojackoPrezime: "Maggio",
        prezime: "Little",
        datumRodjenja: "1967-07-30T07:38:11.829Z",
        mjestoRodjenja: "South Lethamouth",
        opstinaRordjenja: "South Lethamouth",
        drzava: "BIH",
        postanskiBroj: "26940",
        adresa: "0473 Satterfield Mall Apt. 371",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "District Configuration Supervisor"
      },
      {
        jmbg: 1635000320056,
        ime: "Damon",
        djevojackoPrezime: "Gottlieb",
        prezime: "Gottlieb",
        datumRodjenja: "1974-07-23T08:31:23.524Z",
        mjestoRodjenja: "Sengerhaven",
        opstinaRordjenja: "Sengerhaven",
        drzava: "BIH",
        postanskiBroj: "36854-9517",
        adresa: "233 Hills Stream Apt. 627",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "District Intranet Representative"
      },
      {
        jmbg: 2789198506799,
        ime: "Verla",
        djevojackoPrezime: "Murphy",
        prezime: "Runte",
        datumRodjenja: "1952-09-21T01:24:29.172Z",
        mjestoRodjenja: "West Coty",
        opstinaRordjenja: "West Coty",
        drzava: "BIH",
        postanskiBroj: "05484-9146",
        adresa: "5626 Hilpert Pass Apt. 364",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "International Intranet Designer"
      },
      {
        jmbg: 7800520253607,
        ime: "Elliott",
        djevojackoPrezime: "Walter",
        prezime: "Schumm",
        datumRodjenja: "1955-10-20T10:08:01.164Z",
        mjestoRodjenja: "New Mervin",
        opstinaRordjenja: "New Mervin",
        drzava: "BIH",
        postanskiBroj: "53148-5302",
        adresa: "115 Anderson Pines Apt. 590",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Future Quality Manager"
      },
      {
        jmbg: 8373507664272,
        ime: "Roman",
        djevojackoPrezime: "Rice",
        prezime: "Kris",
        datumRodjenja: "1954-09-26T03:24:51.552Z",
        mjestoRodjenja: "West Jalynshire",
        opstinaRordjenja: "West Jalynshire",
        drzava: "BIH",
        postanskiBroj: "57353",
        adresa: "166 Stephania Terrace Apt. 385",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Principal Metrics Representative"
      },
      {
        jmbg: 5999792257605,
        ime: "Adan",
        djevojackoPrezime: "Zboncak",
        prezime: "Collier",
        datumRodjenja: "1973-07-31T19:05:03.400Z",
        mjestoRodjenja: "East Glenda",
        opstinaRordjenja: "East Glenda",
        drzava: "BIH",
        postanskiBroj: "26865-6244",
        adresa: "308 Abbott Turnpike Suite 555",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Legacy Mobility Technician"
      },
      {
        jmbg: 6690173323389,
        ime: "Hershel",
        djevojackoPrezime: "Osinski",
        prezime: "Powlowski",
        datumRodjenja: "1963-10-19T06:23:12.321Z",
        mjestoRodjenja: "Yeseniahaven",
        opstinaRordjenja: "Yeseniahaven",
        drzava: "BIH",
        postanskiBroj: "49367",
        adresa: "339 Marks Turnpike Apt. 685",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Human Mobility Representative"
      },
      {
        jmbg: 2204970738521,
        ime: "Roger",
        djevojackoPrezime: "Breitenberg",
        prezime: "Marquardt",
        datumRodjenja: "1957-05-05T12:23:59.076Z",
        mjestoRodjenja: "South Georgettefort",
        opstinaRordjenja: "South Georgettefort",
        drzava: "BIH",
        postanskiBroj: "95420",
        adresa: "79367 Gerson Fort Suite 368",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Senior Interactions Coordinator"
      },
      {
        jmbg: 4580488085997,
        ime: "Destini",
        djevojackoPrezime: "Berge",
        prezime: "Schinner",
        datumRodjenja: "1961-08-31T00:06:03.173Z",
        mjestoRodjenja: "Lake Van",
        opstinaRordjenja: "Lake Van",
        drzava: "BIH",
        postanskiBroj: "84902-7789",
        adresa: "0115 Nader Point Apt. 189",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Senior Integration Facilitator"
      },
      {
        jmbg: 8309655904503,
        ime: "Amy",
        djevojackoPrezime: "Willms",
        prezime: "Erdman",
        datumRodjenja: "1978-11-21T19:47:56.574Z",
        mjestoRodjenja: "Lake Ebony",
        opstinaRordjenja: "Lake Ebony",
        drzava: "BIH",
        postanskiBroj: "20986",
        adresa: "10745 Witting Plains Suite 948",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Senior Accountability Director"
      },
      {
        jmbg: 7901592756375,
        ime: "Tony",
        djevojackoPrezime: "Ziemann",
        prezime: "Ruecker",
        datumRodjenja: "1956-06-29T16:47:55.757Z",
        mjestoRodjenja: "Leuschkeborough",
        opstinaRordjenja: "Leuschkeborough",
        drzava: "BIH",
        postanskiBroj: "74002-4668",
        adresa: "90950 Katlyn Valleys Suite 286",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Global Response Architect"
      },
      {
        jmbg: 5533176154641,
        ime: "Stanley",
        djevojackoPrezime: "Swaniawski",
        prezime: "Streich",
        datumRodjenja: "1961-06-28T13:19:20.224Z",
        mjestoRodjenja: "East Enrique",
        opstinaRordjenja: "East Enrique",
        drzava: "BIH",
        postanskiBroj: "56782-1350",
        adresa: "965 Lemuel Row Suite 839",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Legacy Tactics Representative"
      },
      {
        jmbg: 2214658853191,
        ime: "Susana",
        djevojackoPrezime: "Halvorson",
        prezime: "Runolfsson",
        datumRodjenja: "1963-06-14T17:48:20.525Z",
        mjestoRodjenja: "Lulustad",
        opstinaRordjenja: "Lulustad",
        drzava: "BIH",
        postanskiBroj: "22726-1231",
        adresa: "62724 Hudson Stravenue Apt. 675",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Forward Communications Specialist"
      },
      {
        jmbg: 7643136338986,
        ime: "Dahlia",
        djevojackoPrezime: "Casper",
        prezime: "Little",
        datumRodjenja: "1957-12-12T01:58:16.300Z",
        mjestoRodjenja: "Schulistmouth",
        opstinaRordjenja: "Schulistmouth",
        drzava: "BIH",
        postanskiBroj: "96085-4817",
        adresa: "0387 Gleichner Motorway Suite 841",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Dynamic Branding Supervisor"
      },
      {
        jmbg: 6650611541027,
        ime: "Sabryna",
        djevojackoPrezime: "Hane",
        prezime: "Will",
        datumRodjenja: "1969-12-22T01:24:45.396Z",
        mjestoRodjenja: "Botsfordberg",
        opstinaRordjenja: "Botsfordberg",
        drzava: "BIH",
        postanskiBroj: "49205-7811",
        adresa: "958 King Rue Apt. 667",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Forward Factors Administrator"
      },
      {
        jmbg: 2910565302771,
        ime: "Leon",
        djevojackoPrezime: "Homenick",
        prezime: "Becker",
        datumRodjenja: "1973-05-16T11:42:37.263Z",
        mjestoRodjenja: "New Jedediah",
        opstinaRordjenja: "New Jedediah",
        drzava: "BIH",
        postanskiBroj: "97110",
        adresa: "7022 Senger Highway Suite 654",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Senior Assurance Coordinator"
      },
      {
        jmbg: 2501415763017,
        ime: "Yoshiko",
        djevojackoPrezime: "Mills",
        prezime: "McCullough",
        datumRodjenja: "1952-05-14T20:39:44.547Z",
        mjestoRodjenja: "Lake Janessa",
        opstinaRordjenja: "Lake Janessa",
        drzava: "BIH",
        postanskiBroj: "54010",
        adresa: "8730 Schinner Stravenue Suite 311",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Forward Communications Developer"
      },
      {
        jmbg: 5071085148269,
        ime: "Noemi",
        djevojackoPrezime: "Weissnat",
        prezime: "Metz",
        datumRodjenja: "1967-07-28T16:12:01.643Z",
        mjestoRodjenja: "North Alenetown",
        opstinaRordjenja: "North Alenetown",
        drzava: "BIH",
        postanskiBroj: "33329-6648",
        adresa: "58192 Rath Springs Apt. 082",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Chief Assurance Producer"
      },
      {
        jmbg: 4432333338469,
        ime: "Leland",
        djevojackoPrezime: "King",
        prezime: "Ebert",
        datumRodjenja: "1971-05-05T19:06:48.535Z",
        mjestoRodjenja: "Adamtown",
        opstinaRordjenja: "Adamtown",
        drzava: "BIH",
        postanskiBroj: "20686-6943",
        adresa: "880 Wade Station Suite 752",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "International Branding Agent"
      },
      {
        jmbg: 4480833420886,
        ime: "Erick",
        djevojackoPrezime: "Moore",
        prezime: "Nikolaus",
        datumRodjenja: "1969-09-13T21:47:00.848Z",
        mjestoRodjenja: "Ankundinghaven",
        opstinaRordjenja: "Ankundinghaven",
        drzava: "BIH",
        postanskiBroj: "59565-3575",
        adresa: "6345 Frederik Village Apt. 847",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Internal Tactics Supervisor"
      },
      {
        jmbg: 7683558200677,
        ime: "Antoinette",
        djevojackoPrezime: "Swift",
        prezime: "Bauch",
        datumRodjenja: "1953-10-08T03:38:28.645Z",
        mjestoRodjenja: "Gibsonfurt",
        opstinaRordjenja: "Gibsonfurt",
        drzava: "BIH",
        postanskiBroj: "58599-6548",
        adresa: "0690 King Mountain Apt. 147",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Human Accounts Architect"
      },
      {
        jmbg: 5369315442866,
        ime: "Talon",
        djevojackoPrezime: "Dach",
        prezime: "Schumm",
        datumRodjenja: "1976-07-01T18:50:14.246Z",
        mjestoRodjenja: "Coltenport",
        opstinaRordjenja: "Coltenport",
        drzava: "BIH",
        postanskiBroj: "43853-4083",
        adresa: "92218 Brandy Bridge Suite 379",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Future Intranet Technician"
      },
      {
        jmbg: 5981665649015,
        ime: "Darrin",
        djevojackoPrezime: "Heller",
        prezime: "Wolff",
        datumRodjenja: "1976-03-18T10:13:53.725Z",
        mjestoRodjenja: "Ociemouth",
        opstinaRordjenja: "Ociemouth",
        drzava: "BIH",
        postanskiBroj: "45552-6128",
        adresa: "0580 Treva Greens Apt. 021",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Human Accounts Executive"
      },
      {
        jmbg: 2114545285964,
        ime: "Nola",
        djevojackoPrezime: "Marvin",
        prezime: "Johns",
        datumRodjenja: "1955-01-15T11:15:34.559Z",
        mjestoRodjenja: "East Fredaton",
        opstinaRordjenja: "East Fredaton",
        drzava: "BIH",
        postanskiBroj: "45099",
        adresa: "0778 Wuckert Village Apt. 317",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Principal Accountability Facilitator"
      },
      {
        jmbg: 1320129105796,
        ime: "Amanda",
        djevojackoPrezime: "Heidenreich",
        prezime: "Schroeder",
        datumRodjenja: "1979-12-29T17:05:27.088Z",
        mjestoRodjenja: "New Bridget",
        opstinaRordjenja: "New Bridget",
        drzava: "BIH",
        postanskiBroj: "80245-8854",
        adresa: "540 Hagenes Trafficway Suite 009",
        drzavljanstvo: "RS/BIH",
        nacionalnaPripadnost: "Srbin",
        vjeroispovjest: "Pravoslavna",
        najvisaZavrsenaSkola: "Srednja",
        zanimanje: "Product Identity Representative"
      }
    ];


router.get('/:jmbg', async (req, res) => {
    const jmbg = req.params.jmbg;

    const result = await majke.filter(x => x.jmbg == jmbg.toString());
    res.status(200).json(
        result
    )
})

router.get('/', async (req,res)=>{
    res.status(200).json(majke);
})

module.exports = router;
