const router = require('express').Router();

const likovi = 
[
  {
    jmbg: 3240875545289,
    ime: "Georgianna",
    prezime: "Luettgen",
    datumRodjenja: "1957-11-25T11:20:41.381Z",
    mjestoRodjenja: "Port Bretburgh",
    opstinaRordjenja: "Port Bretburgh",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Principal Optimization Officer"
  },
  {
    jmbg: 7195353740740,
    ime: "Jaunita",
    prezime: "Waters",
    datumRodjenja: "1959-09-03T22:23:02.247Z",
    mjestoRodjenja: "East Bessiemouth",
    opstinaRordjenja: "East Bessiemouth",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Central Accounts Technician"
  },
  {
    jmbg: 5636071537391,
    ime: "Danielle",
    prezime: "Gaylord",
    datumRodjenja: "1961-10-19T04:22:06.382Z",
    mjestoRodjenja: "Quintonborough",
    opstinaRordjenja: "Quintonborough",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Dynamic Web Designer"
  },
  {
    jmbg: 4308402865144,
    ime: "Precious",
    prezime: "Gislason",
    datumRodjenja: "1953-02-25T00:15:51.777Z",
    mjestoRodjenja: "Lake Nellefurt",
    opstinaRordjenja: "Lake Nellefurt",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Investor Functionality Assistant"
  },
  {
    jmbg: 4483203351381,
    ime: "Raven",
    prezime: "Roob",
    datumRodjenja: "1962-02-20T07:36:57.256Z",
    mjestoRodjenja: "D'Amorebury",
    opstinaRordjenja: "D'Amorebury",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Product Interactions Executive"
  },
  {
    jmbg: 9558449872946,
    ime: "Tania",
    prezime: "Jacobson",
    datumRodjenja: "1964-11-02T05:26:01.379Z",
    mjestoRodjenja: "Jaspermouth",
    opstinaRordjenja: "Jaspermouth",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Forward Assurance Strategist"
  },
  {
    jmbg: 6421446958931,
    ime: "Mabel",
    prezime: "Waelchi",
    datumRodjenja: "1960-08-07T19:20:47.768Z",
    mjestoRodjenja: "East Orin",
    opstinaRordjenja: "East Orin",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Product Markets Officer"
  },
  {
    jmbg: 2610920751597,
    ime: "Davion",
    prezime: "Simonis",
    datumRodjenja: "1978-03-20T01:32:51.570Z",
    mjestoRodjenja: "New Ike",
    opstinaRordjenja: "New Ike",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Future Brand Coordinator"
  },
  {
    jmbg: 9321103134058,
    ime: "Quinton",
    prezime: "Marquardt",
    datumRodjenja: "1978-03-17T19:08:14.972Z",
    mjestoRodjenja: "Letaside",
    opstinaRordjenja: "Letaside",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Future Functionality Consultant"
  },
  {
    jmbg: 1467734025110,
    ime: "Hollis",
    prezime: "Borer",
    datumRodjenja: "1972-05-30T10:56:27.345Z",
    mjestoRodjenja: "Whiteland",
    opstinaRordjenja: "Whiteland",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Lead Assurance Consultant"
  },
  {
    jmbg: 2859005205520,
    ime: "Rico",
    prezime: "Bechtelar",
    datumRodjenja: "1977-04-08T19:21:52.863Z",
    mjestoRodjenja: "Port Gisselle",
    opstinaRordjenja: "Port Gisselle",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Investor Mobility Architect"
  },
  {
    jmbg: 9966822557096,
    ime: "Ora",
    prezime: "Luettgen",
    datumRodjenja: "1976-05-19T19:18:53.863Z",
    mjestoRodjenja: "East Cordiaborough",
    opstinaRordjenja: "East Cordiaborough",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "National Group Strategist"
  },
  {
    jmbg: 7615037508802,
    ime: "Owen",
    prezime: "Thiel",
    datumRodjenja: "1966-08-15T00:11:41.204Z",
    mjestoRodjenja: "New Bereniceland",
    opstinaRordjenja: "New Bereniceland",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "District Assurance Specialist"
  },
  {
    jmbg: 6296610370738,
    ime: "Zena",
    prezime: "Zulauf",
    datumRodjenja: "1960-01-29T18:45:05.113Z",
    mjestoRodjenja: "Emersonport",
    opstinaRordjenja: "Emersonport",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Senior Assurance Developer"
  },
  {
    jmbg: 2747396193196,
    ime: "Katrina",
    prezime: "Yundt",
    datumRodjenja: "1972-02-09T01:19:06.337Z",
    mjestoRodjenja: "Shawnshire",
    opstinaRordjenja: "Shawnshire",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Forward Infrastructure Assistant"
  },
  {
    jmbg: 2965883140818,
    ime: "Milford",
    prezime: "Bruen",
    datumRodjenja: "1961-09-06T00:03:22.534Z",
    mjestoRodjenja: "Doylebury",
    opstinaRordjenja: "Doylebury",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Internal Communications Supervisor"
  },
  {
    jmbg: 8685209167590,
    ime: "Lester",
    prezime: "Cronin",
    datumRodjenja: "1952-10-08T01:56:37.421Z",
    mjestoRodjenja: "South Hilarioshire",
    opstinaRordjenja: "South Hilarioshire",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Dynamic Data Executive"
  },
  {
    jmbg: 3936508526689,
    ime: "Litzy",
    prezime: "Mitchell",
    datumRodjenja: "1979-12-17T06:28:32.321Z",
    mjestoRodjenja: "Hegmanntown",
    opstinaRordjenja: "Hegmanntown",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Corporate Division Consultant"
  },
  {
    jmbg: 4573003176596,
    ime: "Kasey",
    prezime: "Jones",
    datumRodjenja: "1955-11-01T23:49:10.252Z",
    mjestoRodjenja: "South Giovannaburgh",
    opstinaRordjenja: "South Giovannaburgh",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Forward Tactics Administrator"
  },
  {
    jmbg: 8307785715334,
    ime: "Enoch",
    prezime: "Jakubowski",
    datumRodjenja: "1954-04-20T16:06:45.420Z",
    mjestoRodjenja: "Lake Scottiefurt",
    opstinaRordjenja: "Lake Scottiefurt",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Corporate Division Agent"
  },
  {
    jmbg: 1328058840073,
    ime: "Brant",
    prezime: "Gerhold",
    datumRodjenja: "1976-09-17T15:07:07.011Z",
    mjestoRodjenja: "Lake Eleanore",
    opstinaRordjenja: "Lake Eleanore",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Customer Marketing Executive"
  },
  {
    jmbg: 6803007551830,
    ime: "Alex",
    prezime: "King",
    datumRodjenja: "1963-07-24T16:08:10.403Z",
    mjestoRodjenja: "East Christopher",
    opstinaRordjenja: "East Christopher",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Human Mobility Specialist"
  },
  {
    jmbg: 1045726039786,
    ime: "Reece",
    prezime: "Mertz",
    datumRodjenja: "1977-09-11T06:31:14.725Z",
    mjestoRodjenja: "Port Mabel",
    opstinaRordjenja: "Port Mabel",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Regional Implementation Assistant"
  },
  {
    jmbg: 4304106062088,
    ime: "Gwendolyn",
    prezime: "Hammes",
    datumRodjenja: "1957-05-21T08:47:50.937Z",
    mjestoRodjenja: "Lake Darrelchester",
    opstinaRordjenja: "Lake Darrelchester",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Senior Applications Assistant"
  },
  {
    jmbg: 5664312718068,
    ime: "Price",
    prezime: "Beahan",
    datumRodjenja: "1953-09-30T02:45:39.914Z",
    mjestoRodjenja: "Cummingsview",
    opstinaRordjenja: "Cummingsview",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Forward Creative Coordinator"
  },
  {
    jmbg: 2401244353213,
    ime: "Rodger",
    prezime: "Champlin",
    datumRodjenja: "1975-02-13T06:55:11.823Z",
    mjestoRodjenja: "Kemmertown",
    opstinaRordjenja: "Kemmertown",
    drzava: "BIH",
    drzavljanstvo: "RS/BIH",
    nacionalnaPripadnost: "Srbin",
    vjeroispovjest: "Pravoslavna",
    najvisaZavrsenaSkola: "Srednja",
    zanimanje: "Senior Brand Associate"
  }
]

router.get('/:jmbg', async (req, res) => {
    const jmbg = req.params.jmbg;

    const result = await likovi.filter(x => x.jmbg == jmbg.toString());
    res.status(200).json(
        result
    )
})

router.get('/', async (req,res)=>{
    res.status(200).json(likovi);
})


module.exports = router;
